
import React from 'react';
import { School, TeamMember, Payslip } from '../../types.ts';

interface PayslipTemplateProps {
    payslip: Payslip;
    member: TeamMember;
    school: School;
}

const PayslipTemplate: React.FC<PayslipTemplateProps> = ({ payslip, member, school }) => {

    const period = new Date(payslip.year, payslip.month).toLocaleString('default', {
        month: 'long',
        year: 'numeric'
    });

    return (
        <div className="p-8 bg-white text-gray-800 font-sans" style={{ width: '210mm', minHeight: '297mm', margin: 'auto' }}>
            <header className="flex justify-between items-start pb-4 border-b-2 border-gray-800">
                <div>
                    {school.logoUrl && <img src={school.logoUrl} alt={`${school.name} Logo`} className="h-20 w-auto" />}
                    <h1 className="text-3xl font-bold mt-2">{school.name}</h1>
                    <p className="text-sm text-gray-600">{school.address}</p>
                </div>
                <div className="text-right">
                    <h2 className="text-4xl font-light uppercase text-gray-600">Payslip</h2>
                    <p className="font-semibold mt-2">For the month of {period}</p>
                </div>
            </header>
            
            <section className="mt-6 grid grid-cols-2 gap-4 text-sm">
                <div>
                    <p><strong>Employee Name:</strong> {member.name}</p>
                    <p><strong>Role:</strong> {member.role}</p>
                </div>
                <div className="text-right">
                    <p><strong>Date Issued:</strong> {new Date().toLocaleDateString()}</p>
                </div>
            </section>
            
            <section className="mt-8 grid grid-cols-2 gap-8">
                <div>
                    <h3 className="text-lg font-semibold border-b pb-1 mb-2">Earnings</h3>
                    <table className="w-full text-sm">
                        <tbody>
                            <tr><td className="py-1">Base Salary</td><td className="py-1 text-right font-mono">₦{payslip.baseSalary.toLocaleString('en-NG', { minimumFractionDigits: 2 })}</td></tr>
                             {payslip.allowances.map(item => (
                                <tr key={item.id}><td className="py-1">{item.name}</td><td className="py-1 text-right font-mono">₦{item.amount.toLocaleString('en-NG', { minimumFractionDigits: 2 })}</td></tr>
                            ))}
                        </tbody>
                        <tfoot className="border-t-2 border-gray-500 font-bold">
                             <tr><td className="pt-2">Gross Salary</td><td className="pt-2 text-right font-mono">₦{payslip.grossSalary.toLocaleString('en-NG', { minimumFractionDigits: 2 })}</td></tr>
                        </tfoot>
                    </table>
                </div>
                 <div>
                    <h3 className="text-lg font-semibold border-b pb-1 mb-2">Deductions</h3>
                    <table className="w-full text-sm">
                        <tbody>
                             <tr><td className="py-1">PAYE Tax</td><td className="py-1 text-right font-mono">₦{payslip.payeTax.toLocaleString('en-NG', { minimumFractionDigits: 2 })}</td></tr>
                             <tr><td className="py-1">Pension Contribution</td><td className="py-1 text-right font-mono">₦{payslip.pension.toLocaleString('en-NG', { minimumFractionDigits: 2 })}</td></tr>
                             {payslip.deductions.map(item => (
                                <tr key={item.id}><td className="py-1">{item.name}</td><td className="py-1 text-right font-mono">₦{item.amount.toLocaleString('en-NG', { minimumFractionDigits: 2 })}</td></tr>
                            ))}
                        </tbody>
                        <tfoot className="border-t-2 border-gray-500 font-bold">
                            <tr><td className="pt-2">Total Deductions</td><td className="pt-2 text-right font-mono">₦{payslip.totalDeductions.toLocaleString('en-NG', { minimumFractionDigits: 2 })}</td></tr>
                        </tfoot>
                    </table>
                </div>
            </section>
            
            <section className="mt-12 bg-gray-100 p-4 rounded-lg text-center">
                <p className="text-lg font-semibold uppercase">Net Salary</p>
                <p className="text-4xl font-bold font-mono text-primary">₦{payslip.netSalary.toLocaleString('en-NG', { minimumFractionDigits: 2 })}</p>
            </section>

             <footer className="text-center text-xs text-gray-500 mt-16 pt-4 border-t">
                <p>This is a computer-generated document and does not require a signature.</p>
                <p>Generated by SchoolFees.NG</p>
            </footer>
        </div>
    );
};

export default PayslipTemplate;